### ISSUE TITLE
SmartAI: Enable some event/actions for gameobjects

### ISSUE THREAD

**Issue by Nqsty** [SunstriderProject/Sunstrider-Issues#118]
Important much:
* SMART_EVENT_SPELLHIT
* SMART_ACTION_SET_DATA

**Comment by kelno** [comment]
"SMART_EVENT_SPELLHIT" cannot be set for gameobject since you cannot actually truly cast a spell on gameobjects, we must use warkaround using invisible creatures like 18849 or 19008 for quest http://www.wowhead.com/quest=10087.

**Comment by kelno** [comment]
SMART_ACTION_SET_DATA seems to be working.

**Comment by kelno** [comment]
SMART_ACTION_SET_DATA seems to be working.
