### ISSUE TITLE
Set a specific gender to a creature/creature_template

### ISSUE THREAD

**Issue by Nqsty** [SunstriderProject/Sunstrider-Issues#124]
Where?

**Comment by kelno** [comment]
This is defined in creature_model_info.
For example for Colonel Jules:
SELECT * FROM creature_model_info WHERE modelid = (SELECT modelid1 FROM creature_template WHERE entry = 22432)

**Comment by kelno** [comment]
This is defined in creature_model_info.
For example for Colonel Jules:
SELECT * FROM creature_model_info WHERE modelid = (SELECT modelid1 FROM creature_template WHERE entry = 22432)
