### ISSUE TITLE
Create a new SAI targets flag system

### ISSUE THREAD

**Issue by kelno** [SunstriderProject/Sunstrider-Issues#42]
We currently are limited on some issues like :
- We'd want some target types potentially returning multiple targets to be limited to only one target (like SMART_TARGET_CREATURE_RANGE).
- We'd want some targets to avoid taking dead creatures into accounts

This could be solved by adding a new "target_flags" column, with for example :
- TARGET_FLAG_IN_COMBAT_ONLY
- TARGET_FLAG_OUT_OF_COMBAT_ONLY
- TARGET_FLAG_UNIQUE_TARGET (this would replace our custom SMARTCAST_UNIQUE_TARGET)
- TARGET_FLAG_CAN_TARGET_DEAD
- TARGET_FLAG_SAME_FACTION
- ...
To be extended later when we find other usages.

Examples of creatures that would benefit for it :
http://wowhead.com/npc=17730 : Should not heal dead monster, or heal out of combat monsters
http://wowhead.com/npc=21126 : Should shield only one target

**Comment by kelno** [comment]
First test implementation here : 
Nqsty/sunstrider@0764dc8f070e230068a222561b965664cb2f86a5

**Comment by kelno** [comment]
TARGET_FLAG_UNIQUE_TARGET
confirmed okay

**Comment by kelno** [comment]
Flags :
TARGET_FLAG_IN_COMBAT_ONLY
TARGET_FLAG_OUT_OF_COMBAT_ONLY
TARGET_FLAG_CAN_TARGET_DEAD
TARGET_FLAG_SAME_FACTION
still need testing

**Comment by Nqsty** [comment]
* TARGET_FLAG_IN_COMBAT_ONLY: not working (pretty sure TARGET_FLAG_OUT_OF_COMBAT_ONLY not working either if it cant tell the diff)
* TARGET_FLAG_CAN_TARGET_DEAD: not working
* TARGET_FLAG_SAME_FACTION: tested with faction 14, not working.

**Comment by kelno** [comment]
TARGET_FLAG_SAME_FACTION okay
Tested with :
EVENT_HAS_AURA (spell 7128, stack 1)
ACTION_MORPH_TO_ENTRY_OR_MODEL (entry 10)
TARGET_CREATURE_RANGE (any)
Creatures with a different faction are not affected

**Comment by kelno** [comment]
TARGET_FLAG_CAN_TARGET_DEAD okay
Tested with:
EVENT_HAS_AURA (spell 7128, stack 1)
ACTION_MORPH_TO_ENTRY_OR_MODEL (entry 10)
TARGET_CREATURE_RANGE (any)
Dead creatures are not affected if flag is not present, but correctly morphed if so.

**Comment by kelno** [comment]
All flags confirmed okay
