### ISSUE TITLE
Refactor npc gossips a bit, add a "menu" concept

### ISSUE THREAD

**Issue by kelno** [SunstriderProject/Sunstrider-Issues#70]
Mainly we'd want to have an additional layer between the creature and the text, this would give us more flexibility in the gossips creations implying options, when this must currently be done in C++.

npc_gossip and game_event_npc_gossip would now point to some 'menu' instead of directly referencing the text.
A menu would be represented by the following tables :
- gossip_menu : id + text id
- gossip_menu_option : the options by menu

The gossip_menu_option is already close to our npc_options, with the following changes :
- We need a new "menu_id" identifier, to link our entry to gossip_menu.
- We also need to remove the reference to the text id there to put a menu id instead, this new column could be called "action_menu_id".
- "Action" could be renamed to option_id (it is actually a reference to enum Gossip_Option).

Note that there is a bit of concept mixing in this table, what we currently have in npc_options are "global" options, applied on every creature if it has the flag given in the entry. Maybe we could put those in a gossip_menu_global_options instead to have a better distinction. Or just, as Trinity, have menu_id = 0 for those.

Also maybe change table "npc_text" name with "gossip_text"

**Comment by Nqsty** [comment]
Related quest :
* http://www.wowhead.com/quest=9803

**Comment by kelno** [comment]
Done in kelno/sunstrider@7095c12c6482613617ede4a6f1a57912913ebca1 and the two next commits
