### ISSUE TITLE
Target of target not always displayed

### ISSUE THREAD

**Issue by Nqsty** [SunstriderProject/Sunstrider-Issues#71]
![Screen](http://i.imgur.com/bsf1e3j.jpg)

**Comment by kelno** [comment]
Probably related to https://github.com/SunstriderProject/Sunstrider-Issues/issues/67

**Comment by kelno** [comment]
Probably fixed with Kelno/Sunstrider@257e2386d0a460c63ffe9b90bf02ff27041f5a34, to confirm.
