### ISSUE TITLE
creature_text & variables problems

### ISSUE THREAD

**Issue by Nqsty** [SunstriderProject/Sunstrider-Issues#72]
No text in chat when the % variable is unknown.
![Screen](https://i.imgur.com/fBmAD8J.jpg)
% variable displayed in balloon.
![Screen2](https://i.imgur.com/dXH63pA.jpg)

Also : $g not working, it just makes disapear the next character.
Example : $glorem  will appear as 'orem'.

Others $ variables are working as intended:
* $n : name
* $c : class
* $r : race
* $b : break line

**Comment by kelno** [comment]
% variables are only used by the players and cannot be used in creature texts.
$ variables are handled by the client and we cannot change the way it handles them.
