### ISSUE TITLE
SMART_ACTION_TELEPORT

### ISSUE THREAD

**Issue by Nqsty** [SunstriderProject/Sunstrider-Issues#74]
Make SMART_ACTION_TELEPORT possible to use more target types when Map id (param1) = 0 :
* Param2 : Visual (0/1) (spell 41232)
* SMART_TARGET_VICTIM
* SMART_TARGET_HOSTILE_SECOND_AGGRO
* SMART_TARGET_HOSTILE_LAST_AGGRO
* SMART_TARGET_HOSTILE_RANDOM
* SMART_TARGET_HOSTILE_RANDOM_NOT_TOP
* SMART_TARGET_POSITION

**Comment by kelno** [comment]
When map = 0, it does not actually mean "do not use map" but "teleport to map 0".
Param 2 is now "ignoreMap"
Param 3 is now "useVisual"

As for the targets given here they seemed to work for me, if not for you then give me an example.

**Comment by kelno** [comment]
Done in kelno/sunstrider@09e8ed4220fd7eab478f738aae23af484646700e
