### ISSUE TITLE
ACTION_SET_ORIENTATION not working

### ISSUE THREAD

**Issue by Nqsty** [SunstriderProject/Sunstrider-Issues#83]
SmartAI : 19273
* .quest add 10208
* .quest complete force 10208
* .go creature id 19273
* Take the next quest, see if the creature points at Wing Commander Brack.

**Comment by kelno** [comment]
qdsqdqdzadqsfgf

**Comment by kelno** [comment]
This was another problem, this is fixed in 
Fixed in Kelno/Sunstrider@e2ae4034628dde3fc2faf69ac314747cff18b3a3, you had the EVENT_TEXT_OVER triggering too soon.
